import { NextApiRequest, NextApiResponse } from "next";

export default function handler(req:NextApiRequest, res: NextApiResponse) {
  res.status(200).json({
    "dragonesBaseDeDatos": [
    {
    "nombreCompleto": "Andres",
    "cc": 1105370878,
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 2
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 3
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 4
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 5
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 6
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 7
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 8
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 9
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 10
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 11
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 12
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 13
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 14
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 15
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 16
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 17
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 18
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 19
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 20
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 21
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 22
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 23
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 24
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 25
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 26
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 27
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 28
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 29
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 30
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 31
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 32
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 33
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 34
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 35
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 36
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 37
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 38
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 39
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 40
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 41
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 42
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 43
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 44
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 45
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 46
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 47
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 48
    },
    {
    "nombreCompleto": "",
    "cc": "",
    "nombreCompletoDelPadre": "",
    "celularDelPadre": "",
    "nombreCompletoDeLaMadre": "",
    "celularDeLaMadre": "",
    "¿enCasoDeEmergenciaAQuienLlamar?": "",
    "númeroTelefónicoEnCasoDeEmergencia": "",
    "dirección": "",
    "fechaDeNacimiento": "",
    "eps": "",
    "enfermedad": "",
    "tipoDeSangre": "",
    "siCuentasConUnaEnfermedad, ¿quéTipoDeEnfermedadTienes? ¿utilizasMedicamentos? ¿cuálesSon?": "",
    "¿cuálEsTuNúmeroDeUniforme?": "",
    "mensajeWhatsaap": "Enviar Mensaje",
    "id": 49
    }
    ]
    })
}